---
- name: Install Nginx
  dnf:
    name: nginx
    state: present

- name: Enable Nginx
  service:
    name: nginx
    enabled: yes

- name: Start Nginx
  service:
    name: nginx
    state: started

- name: Deploy nginx site config
  template:
    src: site.conf.j2
    dest: /etc/nginx/conf.d/site.conf
  notify: Restart Nginx    
