---
- name: Install Nginx
  dnf:
    name: nginx
    state: present

- name: Enable Nginx
  service:
    name: nginx
    enabled: yes

- name: Start Nginx
  service:
    name: nginx
    state: started
