---
- name: Install MariaDB 10.11
  dnf:
    name:
      - mariadb1011-server
      - mariadb1011
    state: present

- name: Enable MariaDB
  service:
    name: mariadb
    enabled: yes

- name: Start MariaDB
  service:
    name: mariadb
    state: started
