---
- name: Install MariaDB server
  ansible.builtin.dnf:
    name:
      - mariadb1011-server
    state: present

- name: Enable MariaDB service
  ansible.builtin.service:
    name: mariadb
    enabled: yes
    state: started

- name: Start MariaDB service
  ansible.builtin.service:
    name: mariadb
    state: started

- name: Install pip
  ansible.builtin.dnf:
    name: python3-pip
    state: present

- name: Install PyMySQL dependency
  ansible.builtin.pip:
    name: PyMySQL


- name: Create WordPress database
  community.mysql.mysql_db:
    name: wordpress
    state: present
    login_user: root
    login_password: Root@123

- name: Create WordPress user
  community.mysql.mysql_user:
    name: wpuser
    password: Wp@123
    priv: "wordpress.*:ALL"
    host: localhost
    state: present
    login_user: root
    login_password: Root@123
