---
- name: Install certbot
  dnf:
    name:
      - certbot
      - python3-certbot-nginx
    state: present

- name: Stop nginx before SSL
  service:
    name: nginx
    state: stopped

- name: Generate SSL certificate
  command: >
    certbot certonly --standalone
    -d yadhurd.xyz
    -d www.yadhurd.xyz
    --non-interactive
    --agree-tos
    --email admin@yadhurd.xyz
  args:
    creates: /etc/letsencrypt/live/yadhurd.xyz/fullchain.pem

- name: Deploy SSL nginx config
  template:
    src: site-ssl.conf.j2
    dest: /etc/nginx/conf.d/site.conf

- name: Start nginx
  service:
    name: nginx
    state: started
    enabled: yes
